version: "2"
services:
    mongo:
        container_name: mongo_qrona
        image: mongo
        volumes:
          - ./data:/data/db
        ports:
          - "27017:27017"
    app:
        container_name: qrona
        restart: always
        build: .
        ports:
        - "2222:3000"
        links:
        - mongo